### ISSUE TITLE
Exception after Flutter Upgrade to 1.9

### ISSUE THREAD

**Issue by patlecat** [Apress/practical-flutter#1]
After the upgrade of Flutter to v1.9 I suddenly got this exception thrown that I didn't see before in your code that I didn't modify btw. Using Android Studio under Windows 10.

> The following NoSuchMethodError was thrown building AppointmentsEntry(dirty):
The getter 'title' was called on null.
Receiver: null
Tried calling: title
User-created ancestor of the error-causing widget was: 
  IndexedStack file:///C:/Development/myFlutterProjects/flutter_book/lib/appointments/Appointments.dart:38:22

**Comment by fzammetti** [comment]
I just checked in an update that brings the project into compliance for the latest version of Flutter (as of 2/15/2020) including updates to most dependencies to their latest and Android SDK 28.  Everything is working for me, hopefully everyone else as well.
